---
parent: 'common/test_cases/crio.yml'
overrides:
  provision:
    os: "rhel"
    stage: "bare"
    provider: "aws"
extensions:
  sync:
    - cri-o,cri-o=master
  actions:
    - type: "host_script"
      title: "install CI user account"
      script: |-
        oct prepare user
        sed -i 's/User ec2-user/User origin/g' ./.config/origin-ci-tool/inventory/.ssh_config
    - type: "host_script"
      title: "bootstrap remote host"
      script: |-
        oct bootstrap host
        oct bootstrap node
    - type: "script"
      title: "install git"
      script: |-
        sudo yum install -y git
    - type: "forward_parameters"
      parameters:
        - PULL_NUMBER
        - PULL_BASE_SHA
        - PULL_PULL_SHA
    - type: "script"
      title: "set up cri-o dependencies"
      script: |-
        ansible-playbook -vv --become  \
                         -i localhost, \
                         --tags setup  \
                         --become-user root \
                         --connection local \
                         /go/src/github.com/cri-o/cri-o/contrib/test/integration/main.yml
    - type: "host_script"
      title: "package the AMI"
      script: |-
        oct package ami --stage=crio
    - type: "script"
      title: "run the cri-o tests"
      timeout: "21600"  # 6 hours.  Playbook has shorter timeout for the test-task.
      script: |-
        ansible-playbook -vv --become  \
                         -i localhost, \
                         --tags integration,critest,e2e,e2e-features \
                         --become-user root \
                         --connection local \
                         /go/src/github.com/cri-o/cri-o/contrib/test/integration/main.yml
