---
parent: 'common/test_cases/crio.yml'
overrides:
  provision:
    os: "rhel"
    stage: "crio"
    provider: "aws"
extensions:
  sync:
    - cri-o,cri-o=master
  actions:
  - type: "forward_parameters"
    parameters:
      - PULL_NUMBER
      - PULL_BASE_SHA
      - PULL_PULL_SHA
  - type: "script"
    title: "run the cri-o integration tests"
    script: |-
      ansible-playbook -vv --become  \
                       -i localhost, \
                       --tags integration \
                       --become-user root \
                       ${EXTRA_EVARS:-} \
                       --connection local \
                       /go/src/github.com/cri-o/cri-o/contrib/test/integration/main.yml
